workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Outpost API:
        inputs:
            - location: ./sdks/schemas/hookdeck-schema.yaml
        overlays:
            - location: ./sdks/schemas/speakeasy-modifications-overlay.yaml
            - location: ./sdks/schemas/error-types.yaml
        registry:
            location: registry.speakeasyapi.dev/hookdeck-dev/outpost/outpost-api
targets:
    outpost-go:
        target: go
        source: Outpost API
        output: ./sdks/go
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/hookdeck-dev/outpost/outpost-api-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
    outpost-python:
        target: python
        source: Outpost API
        output: ./sdks/python
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/hookdeck-dev/outpost/outpost-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
    outpost-ts:
        target: typescript
        source: Outpost API
        output: ./sdks/typescript
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/hookdeck-dev/outpost/outpost-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
