auth:
  username: outpost

replicaCount: 1

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

metrics:
  enabled: false
