name: "outpost-loadtest"

services:
  mock-webhook:
    build:
      context: ./mock/webhook
      dockerfile: Dockerfile
    ports:
      - "48080:8080"
    environment:
      - PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "46379:6379"
    command: redis-server
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped
