name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      # enable Buildx manifest support
      DOCKER_CLI_EXPERIMENTAL: "enabled"
      # still expose the secret if you need it elsewhere in run-scripts
      ACR_NAME: ${{ secrets.ACR_NAME }}

    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install JS dependencies
        run: npm install
        working-directory: internal/portal

      - name: Build Portal
        run: npm run build
        working-directory: internal/portal

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        uses: azure/docker-login@v1
        with:
          # inline the computed login server here
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io

      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release -f build/.goreleaser.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GoReleaser will pick this up if your YAML references .Env.ACR_LOGIN_SERVER
          ACR_LOGIN_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
