name: Unit Tests

on:
  push:
    branches:
      - main # Adjust 'main' if your primary branch is named differently (e.g., master)
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Run unit tests
        run: make test/unit